Portfolio/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace Portfolio.Models
{
    public class Contact
    {
        [Key]
        public int ContactId { get; set; }
        public string? Name { get; set; }
        public int? Number { get; set; }
        public string? Email { get; set; }
        public string? Country { get; set; }
        public string? Message { get; set; }

        public DateTime CreatedDateTime { get; set; } = DateTime.Now;

    }
}

Portfolio/Models/ErrorViewModel.cs
namespace Portfolio.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Portfolio/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace Portfolio.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Portfolio/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using Portfolio.Data;
using Portfolio.Models;

namespace Portfolio.Controllers
{
    public class ContactController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ContactController (ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //IEnumerable<Contact> objContactList = _db.Contacts;
            //return View(objContactList);
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Contact model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    _db.Contacts.Add(model);
                    _db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                throw;
            }
            return View(model);
        }
    }
}

Portfolio/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Portfolio.Models;
using System.Diagnostics;

namespace Portfolio.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Portfolio/Controllers/ResumeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Portfolio.Controllers
{
    public class ResumeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Portfolio/Views/Blog/Index.cshtml
@{
    ViewData["Title"] = "Blog Page";
}


<style>
    /* body {
        font-family: Arial, sans-serif;
        text-align: center;
        margin: 20px;
    }*/

    .containerForm {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 2px solid #ccc;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
        margin-bottom: 20px;
    }

    label, input, select {
        display: block;
        margin-bottom: 10px;
    }

    input, select {
        width: 100%;
        padding: 8px;
        font-size: 16px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button {
        margin-top: 10px;
        background-color: #4CAF50;
        color: #fff;
        padding: 10px 20px;
        font-size: 16px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        button:hover {
            background-color: #45a049;
        }

    p {
        font-weight: bold;
        margin-top: 20px;
    }

</style>

<section id="about" class="about">
    <div class="container">

        <div class="section-title">
            <h2>Position size calculator</h2>
            <p></p>
        </div>

        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="containerForm">
                            <h1>Position Sizing Calculator</h1>
                            <label for="accountBalance">Account Balance ($):</label>
                            <input type="number" id="accountBalance" min="1" step="1">

                            <label for="riskPercentage">Risk Percentage (%):</label>
                            <input type="number" id="riskPercentage" min="0.1" step="0.1">

                            <label for="entryPrice">Entry Price ($):</label>
                            <input type="number" id="entryPrice" min="1" step="0.01">

                            <label for="stopLoss">Stop Loss ($):</label>
                            <input type="number" id="stopLoss" min="1" step="0.01">

                            <label for="positionType">Position Type:</label>
                            <select id="positionType">
                                <option value="long">Long</option>
                                <option value="short">Short</option>
                            </select>
                            <button onclick="calculatePositionSize()">Calculate</button>
                            <p>Position Size: <span id="positionSize">-</span></p>
                        </div>

                    </div>
                </div>
            </div>
        </main>
    </div>
</section><!-- End About Section -->


<script>
    function calculatePositionSize() {
        const accountBalance = parseFloat(document.getElementById('accountBalance').value);
        const riskPercentage = parseFloat(document.getElementById('riskPercentage').value);
        const entryPrice = parseFloat(document.getElementById('entryPrice').value);
        const stopLoss = parseFloat(document.getElementById('stopLoss').value);
        const positionType = document.getElementById('positionType').value;

        if (isNaN(accountBalance) || isNaN(riskPercentage) || isNaN(stopLoss) || isNaN(entryPrice)) {
            alert('Please enter valid numbers for all inputs.');
            return;
        }

        const riskAmount = (accountBalance * riskPercentage) / 100;
        let positionSize;

        if (positionType === 'long') {
            positionSize = Math.floor(riskAmount / (entryPrice - stopLoss));
        } else if (positionType === 'short') {
            positionSize = Math.floor(riskAmount / (stopLoss - entryPrice));
        }

        document.getElementById('positionSize').innerText = positionSize;
    }


</script>

Portfolio/Views/Contact/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Portfolio/Views/Contact/Index.cshtml
@model Contact
@{
    ViewData["Title"] = "Home Page";
}
@{

}

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container">

        <div class="section-title">
          <h2>Contact</h2>
          <p>Get in touch with me.</p>
        </div>

        <div class="row" data-aos="fade-in">

          <div class="col-lg-5 d-flex align-items-stretch">
            <div class="info">
              <div class="address">
                <i class="bi bi-geo-alt"></i>
                <h4>Location:</h4>
                <p>Nepal, Bhaktapur</p>
              </div>

              <div class="email">
                <i class="bi bi-envelope"></i>
                <h4>Email:</h4>
                <p>Saurab.shrestha1010@gmail.com</p>
              </div>

              <div class="phone">
                <i class="bi bi-phone"></i>
                <h4>Call:</h4>
                <p>+977 9843199977</p>
              </div>
              <iframe
						src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7066.639975872377!2d85.36995653488769!3d27.676503300000014!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb1a13269174b9%3A0x8b9583c158c7f911!2sGatthaghar%2C%20Madhyapur%20Thimi%2044600!5e0!3m2!1sen!2snp!4v1662454297537!5m2!1sen!2snp"
						frameborder="0" style="border:0; width:100%; height:290px;" allowfullscreen="" loading="lazy"
						referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>

          </div>

          <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch">
            <form asp-action="Create" id="ContactSubmit" autocomplete="off" class="php-email-form">
                 <div asp-validation-summary="ModelOnly" class="text-danger"></div>
              <div class="row">
                <div class="form-group col-md-6">
                 <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" id="name" required/>
                <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                  <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" required/>
                <span asp-validation-for="Number" class="text-danger"></span>
                </div>
              </div>
              <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input type = "email" asp-for="Email" class="form-control" required/>
                <span asp-validation-for="Email" class="text-danger"></span>
              </div>
              <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input type = "Country" asp-for="Country" class="form-control" required/>
                <span asp-validation-for="Country" class="text-danger"></span>
              </div>
              <div class="form-group">
               <label asp-for="Message" class="control-label"></label>
             @*   <input asp-for="Message" class="form-control" required/>*@
                <textarea class="form-control" name="message" rows="10" required></textarea>
                <span asp-validation-for="Message" class="text-danger"></span>
              </div>
             @* <div class="my-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>*@
              <br />
              <div class="text-center"><button type="submit">Send Message</button></div>
              
             @* <div class="form-group">
                <input type="submit" id="SubmitButton" value="Create" class="btn btn-primary" />
            </div>*@
            </form>
          </div>

        </div>

      </div>

    </section><!-- End Contact Section -->
      <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

     <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
      <script src="assets/vendor/aos/aos.js"></script>
     <script type="text/javascript">

    $("SubmitButton").click(function(){
        debugger;
        var form = $("#ContactSubmit").serialize();
        $.ajax({
            url: "@Url.Action("Create", "Contact")",
            type: "POST",
            dataType: 'json',
            success: function(data){
                $.notify('MEssage Sent Successfully', {globalPosition: 'top center', className: 'success'});
            },
            error: function(){
                alert("Error");
            }
        })
    })



</script>

Portfolio/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<section id="about" class="about">
      <div class="container">

        <div class="section-title">
          <h2>Saurab Shrestha</h2>
          <p>Hello World! I am Saurab Shrestha, I work with asp.net core, umbraco, sql server management studio and jQuery. </p>
        </div>

        <div class="row">
          <div class="col-lg-4" data-aos="fade-right">
            <img src= "~/Images/Image-1.jpg" class="img-fluid" alt="">
          </div>
          <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
            <h3>Web Developer.</h3>
            <p class="fst-italic">
              Get to know me!
            </p>
            <div class="row">
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-chevron-right"></i> <strong>Birthday:</strong> <span>16 Feb 1999</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <span>https://github.com/Saurab-1010</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong> <span>+977 9843199977</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>City:</strong> <span>Bhaktapur, Nepal</span></li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-chevron-right"></i> <strong>Age:</strong> <span>25</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Degree:</strong> <span>Bachelors</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Email:</strong> <span>saurab.shrestha1010@gmail.com</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Freelance:</strong> <span>Available</span></li>
                </ul>
              </div>
            </div>
            <p>
               .
            </p>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->

Portfolio/Views/Resume/Index.cshtml
@{
    ViewData["Title"] = "Resume Page";
}

<section id="resume" class="resume">
      <div class="container">

        <div class="section-title">
          <h2>Resume</h2>
          <p> Hello World! This is my resume, if you need more information about be you can contact me.</p>
        </div>

        <div class="row">
          <div class="col-lg-6" data-aos="fade-up">
            <h3 class="resume-title">Sumary</h3>
            <div class="resume-item pb-0">
              <h4>Saurab Shrestha</h4>
              <p><em>Innovative and deadline-driven web devloper with 1+ years of experience designing and developing user-centered web pages from initial concept to final, polished deliverable.</em></p>
              <ul>
                <li>Nepal,Bhaktapur</li>
                <li>+977 9843199977</li>
                <li>saurab.shrestha1010@gmail.com</li>
              </ul>
            </div>

            <h3 class="resume-title">Education</h3>
@*            <div class="resume-item">
              <h4>Master of Fine Arts &amp; Graphic Design</h4>
              <h5>2015 - 2016</h5>
              <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
              <p>Qui deserunt veniam. Et sed aliquam labore tempore sed quisquam iusto autem sit. Ea vero voluptatum qui ut dignissimos deleniti nerada porti sand markend</p>
            </div>*@
            <div class="resume-item">
              <h4>Bachelor of Information Management</h4>
              <h5>2016 - 2020</h5>
              <p><em>Thames International College, Kathmandu</em></p>
              <p> I have completed my Bachelors from Thames International College affiliated with Tribhuvan University. The course consist of Management and IT fileds.</p>
            </div>
          </div>
          <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">
            <h3 class="resume-title">Professional Experience</h3>
            <div class="resume-item">
              <h4>ASP.NET junior UMBRACO Developer</h4>
              <h5>2022 - present</h5>
              <p><em>Usome Solutions </em></p>
              <ul>
                <li>Worked in the Umbraco CMS</li>
                <li>Developed website using asp.net core and Umbraco</li>
                <li>fixing bugs and developing site.</li>
                <li>junior full stack developer</li>
              </ul>
            </div>
            <div class="resume-item">
              <h4>Intern</h4>
              <h5>2022</h5>
              <p><em>Isewa</em></p>
              <ul>
                <li>Learned about the web development.</li>
                <li>Developed small website using MVC and Crud operation with jquery</li>
                <li>Managed website content</li>
                <li>Solving minor bugs in the site</li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </section><!-- End Resume Section -->

Portfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Portfolio.styles.css" asp-append-version="true" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

</head>
<style>
    .nav {
        background-color: #f1f1f1; /* Gray color */
        padding: 10px; /* Add some padding for spacing */
    }

      .nav-item {
        margin: 0 10px; /* Add margin between navigation items */
    }

    .nav-link {
        font-size: 20px;
        color: #333; /* Text color */
        text-decoration: none; /* Remove underline */
        transition: color 0.3s ease; /* Add smooth transition for color change */
    }

    .nav-link:hover {
        color: #555; /* Hover state color */
    }

    .nav-item.active {
        background-color: #ddd; /* Active state background color */
    }

   .footer {
        display: flex;
        justify-content: flex-start;
        align-items: center;
    }

    .footer-icons {
        margin-right: 10px;
    }
</style>
<body>
    <header>
        <nav>
                    <ul class="nav justify-content-center">
                         <li class="nav-item">
                             <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                           </li>
                        <li class="nav-item">
                            <a class="nav-link"  asp-area="" asp-controller="Resume" asp-action="Index">Resume</a>
                             </li>
                        <li class="nav-item">
                             <a class="nav-link"  asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                          </li>
                    </ul> 
           
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="nav justify-content-center">
        <div class="nav-item">
           <div class="footer-icons">
                  <a href="https://github.com/Saurab-1010" target="_blank" rel="noopener noreferrer">
            <i class="fab fa-github fa-2x"></i>
           <a href="https://www.linkedin.com/in/asp-net/" target="_blank" rel="noopener noreferrer">
            <i class="fab fa-linkedin fa-2x"></i>
            </a>
           <a href="https://twitter.com/Saurab1010" target="_blank" rel="noopener noreferrer">
            <i class="fab fa-twitter fa-2x"></i>
        </a>
        </a>
        &copy; 2023 -Saurab Portfolio
        </div>

    </footer>

     <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
    window.onload = function() {
        // Get the current URL path
        var path = window.location.pathname;
        
        // Get all navigation links
        var navLinks = document.querySelectorAll('.nav-link');
        
        // Loop through the links and add the 'active' class to the one that matches the current URL path
        for (var i = 0; i < navLinks.length; i++) {
            if (navLinks[i].getAttribute('href') === path) {
                navLinks[i].parentElement.classList.add('active');
                break; // Stop the loop once a match is found
            }
        }
    };

</script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>